---
#Groups are nice for organization, but thatâ€™s not all groups are good for. 
# You can also assign variables to them! 
# For instance, atlanta has its own NTP servers, so when setting up ntp.conf, we should use them.
#
# This applies to this bit of `hosts`:
# [atlanta:children]
# atlanta-webservers
# atlanta-dbservers

ntp: ntp-atlanta.example.com
backup: backup-atlanta.example.com
